// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Lee una variable de entorno obligatoria desde el `.env` cargado.
  ///
  /// Si el `.env` desplegado está vacío o incompleto (por ejemplo, el
  /// placeholder vacío que genera `setup.bat`), esto lanza un [StateError]
  /// explícito en vez de dejar que Firebase falle en silencio con
  /// credenciales vacías, lo que antes producía una pantalla en blanco sin
  /// ningún mensaje de error.
  static String _requireEnv(String key) {
    final value = dotenv.env[key];
    if (value == null || value.isEmpty) {
      throw StateError(
        'Falta la variable de entorno "$key" en el archivo .env desplegado. '
        'Verifica que el build actual se haya compilado con un .env real '
        '(no vacío) antes de hacer deploy.',
      );
    }
    return value;
  }

  static FirebaseOptions get web {
    final projectId = _requireEnv('PROJECT_ID');
    return FirebaseOptions(
      apiKey: _requireEnv('WEB_API_KEY'),
      appId: _requireEnv('WEB_APP_ID'),
      messagingSenderId: _requireEnv('MESSAGING_SENDER_ID'),
      projectId: projectId,
      authDomain: '$projectId.firebaseapp.com',
      storageBucket: _requireEnv('STORAGE_BUCKET'),
      measurementId: 'G-22KGS61ZSB',
    );
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY'] ?? '',
    appId: dotenv.env['ANDROID_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID'] ?? '',
    projectId: dotenv.env['PROJECT_ID'] ?? '',
    storageBucket: dotenv.env['STORAGE_BUCKET'] ?? '',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY'] ?? '',
    appId: dotenv.env['IOS_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID'] ?? '',
    projectId: dotenv.env['PROJECT_ID'] ?? '',
    storageBucket: dotenv.env['STORAGE_BUCKET'] ?? '',
    iosBundleId: dotenv.env['IOS_BUNDLE_ID'] ?? '',
  );

}